In [5]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score

In [24]:
%cd C:

titanic = pd.read_csv(r"C:\DeepLearning\Lab_part_04\titanic.csv")

print(titanic.shape)

pd.set_option("display.max_columns", 50)

titanic.head()

C:\Users\ADMIN\Untitled Folder
(1309, 15)

,passenger_id,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,1,"Allen, Miss. Elisabeth Walton",1,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,2,1,1,"Allison, Master. Hudson Trevor",0,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,3,1,0,"Allison, Miss. Helen Loraine",1,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,4,1,0,"Allison, Mr. Hudson Joshua Creighton",0,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,5,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [25]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   passenger_id  1309 non-null   int64
 1   pclass        1309 non-null   int64
 2   survived      1309 non-null   int64
 3   name          1309 non-null   int64
 4   sex           1309 non-null   int64
 5   age           1309 non-null   int64
 6   sibsp         1309 non-null   int64
 7   parch         1309 non-null   int64
 8   ticket        1309 non-null   int64
 9   fare          1309 non-null   int64
 10  cabin         1309 non-null   int64
 11  embarked      1309 non-null   int64
 12  boat          1309 non-null   int64
 13  body          1309 non-null   int64
 14  home.dest     1309 non-null   int64
dtypes: int64(15)
memory usage: 153.5 KB

,passenger_id,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
count,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000
mean,654.000000,1.294882,0.381971,652.689076,0.355997,42.624905,0.485103,0.381971,463.625668,122.178762,83.786096,1.493506,7.116119,5.546218,213.273491
std,378.020061,0.837836,0.486055,377.309849,0.478997,17.963666,0.951805,0.838219,278.069490,79.943406,25.790353,0.814244,6.214462,20.374072,79.852770
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,327.000000,1.000000,0.000000,326.000000,0.000000,32.000000,0.000000,0.000000,212.000000,49.000000,80.000000,1.000000,4.000000,0.000000,195.000000
50%,654.000000,2.000000,0.000000,652.000000,0.000000,36.000000,0.000000,0.000000,459.000000,111.000000,80.000000,2.000000,4.000000,0.000000,236.000000
75%,981.000000,2.000000,1.000000,979.000000,1.000000,53.000000,1.000000,0.000000,727.000000,181.000000,80.000000,2.000000,8.000000,0.000000,236.000000
max,1308.000000,2.000000,1.000000,1306.000000,1.000000,97.000000,6.000000,7.000000,928.000000,280.000000,185.000000,2.000000,26.000000,120.000000,368.000000

In [26]:
imputer = SimpleImputer(strategy='most_frequent')
df = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

In [27]:
le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

In [28]:
X = df.drop("survived", axis=1)
y = df["survived"]

In [29]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

models = {
    "Logistic Regression": LogisticRegression(max_iter=5000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC()
}

for name, model in models.items():

    scores = cross_val_score(model, X, y, cv=5)

    print(name)
    print("Scores:", scores)
    print("Average Accuracy:", scores.mean())
    print("--------------------")

Logistic Regression
Scores: [0.73282443 0.92366412 0.78625954 0.79007634 0.78927203]
Average Accuracy: 0.8044192916264514
--------------------
Decision Tree
Scores: [0.4389313  0.90076336 0.7480916  0.72137405 0.63218391]
Average Accuracy: 0.6882688426778978
--------------------
Random Forest
Scores: [0.40076336 0.77862595 0.69465649 0.58396947 0.65517241]
Average Accuracy: 0.6226375361937352
--------------------
SVM
Scores: [0.72519084 0.90076336 0.80152672 0.7519084  0.76245211]
Average Accuracy: 0.7883682840513584
--------------------

In [30]:
for name, model in models.items():
    
    scores = cross_val_score(model, X, y, cv=5)
    
    print(name)
    print("Scores:", scores)
    print("Average Accuracy:", scores.mean())
    print("--------------------")

Logistic Regression
Scores: [0.73282443 0.92366412 0.78625954 0.79007634 0.78927203]
Average Accuracy: 0.8044192916264514
--------------------
Decision Tree
Scores: [0.45038168 0.91221374 0.76717557 0.70229008 0.63218391]
Average Accuracy: 0.6928489953496534
--------------------
Random Forest
Scores: [0.39694656 0.78625954 0.75954198 0.54198473 0.63984674]
Average Accuracy: 0.6249159135444999
--------------------
SVM
Scores: [0.72519084 0.90076336 0.80152672 0.7519084  0.76245211]
Average Accuracy: 0.7883682840513584
--------------------

In [31]:
skf = StratifiedKFold(n_splits=5)

for name, model in models.items():
    
    scores = cross_val_score(model, X, y, cv=skf)
    
    print(name)
    print("Stratified Accuracy:", scores.mean())
    print("--------------------")

Logistic Regression
Stratified Accuracy: 0.8044192916264514
--------------------
Decision Tree
Stratified Accuracy: 0.6699482319908748
--------------------
Random Forest
Stratified Accuracy: 0.6562048492293293
--------------------
SVM
Stratified Accuracy: 0.7883682840513584
--------------------

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier()

model.fit(X_train, y_train)

train_acc = model.score(X_train, y_train)
test_acc = model.score(X_test, y_test)

print("Train Accuracy:", train_acc)
print("Test Accuracy:", test_acc)

Train Accuracy: 1.0
Test Accuracy: 0.9274809160305344